apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::017325602810:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-J0CFLO118ON9
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-28T14:57:27Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1285"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 3fb31441-cb54-40db-bad2-052b1e35d939
